# Generated by Django 5.1.6 on 2026-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
