# Generated by Django 5.1.6 on 2026-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=20)),
                ('emp_phone', models.IntegerField(max_length=10)),
                ('emp_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
