# Generated by Django 5.1.6 on 2026-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_employeedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='emp_phone',
        ),
    ]
