# Generated by Django 5.1.6 on 2026-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0003_remove_employeedetails_emp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='emp_phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
