# Generated by Django 5.1.6 on 2026-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0005_alter_employeedetails_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_phone',
            field=models.CharField(max_length=15),
        ),
    ]
