# Generated by Django 5.1.6 on 2026-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_alter_employeedetails_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_pass',
            field=models.CharField(max_length=100),
        ),
    ]
